name: media_manipulations
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  # ffmpeg_kit_flutter_full: ^6.0.3
  flutter_bloc: ^9.1.0
  path: ^1.9.0
  image_picker: ^1.1.2
  injectable: ^2.5.0
  get_it: ^8.0.3
  bloc: ^9.0.0
  equatable: ^2.0.7
  permission_handler: ^12.0.0+1
  path_provider: ^2.1.5
  chewie: ^1.11.0
  audioplayers: ^6.4.0
  flutter_colorpicker: ^1.1.0
  ffmpeg_kit_flutter_full_gpl: ^6.0.3
  # image: ^4.5.4
  # video_player: ^2.9.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  dev: ^1.0.0
  colorize: ^3.0.0
  injectable_generator: ^2.7.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/Roboto-Regular.ttf
